### ISSUE TITLE
依赖之后, app崩溃

### ISSUE THREAD

**Issue by OvenCroc** [season-max/asm_hook#1]
大兄弟, 依赖你的库之后, app启动就崩溃, 提示找不到CoreComponentFactory这个类, 请问有解决办法么, 有么有联系方式方便加你一下呢

**Comment by GitJoBo** [comment]
解决了吗？我这也遇到了

**Comment by OvenCroc** [comment]
没有呢, 你解决了嘛大兄弟

> 解决了吗？我这也遇到了

**Comment by season-max** [comment]
依赖工具类不要使用远程依赖的方式了，直接使用本地依赖试试

**Comment by OvenCroc** [comment]
我依赖的就是本地的呢 本地打了个plugin和toollibrary的aar包  跑起来一样的效果,还是会崩溃, plugin里面的insertWriteToFileMethod 注释掉就没有问题, 只是没有拦截系统的方法.
![image](https://user-images.githubusercontent.com/10048606/185364983-d0d6565a-4826-46b3-8773-4d2686d4e95a.png)

**Comment by season-max** [comment]
[https://stackoverflow.com/questions/57438312/java-lang-classnotfoundexception-didnt-find-class-com-my-app-name-androidx](https://stackoverflow.com/questions/57438312/java-lang-classnotfoundexception-didnt-find-class-com-my-app-name-androidx)
你 google 下解决方案，看样子是 androidx 和 android support 冲突的问题。

**Comment by GitJoBo** [comment]
我直接下载demo也是这个错误
`2022-08-30 09:49:13.726 2482-2482/com.zhangyue.ireader.asm_hook E/LoadedApk: Unable to instantiate appComponentFactory
    java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.CoreComponentFactory" on path: DexPathList[[zip file "/data/app/com.zhangyue.ireader.asm_hook-2qV3WnGX1elKmKWhY32UGw==/base.apk"],nativeLibraryDirectories=[/data/app/com.zhangyue.ireader.asm_hook-2qV3WnGX1elKmKWhY32UGw==/lib/arm64, /system/lib64, /system/vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:171)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.LoadedApk.createAppFactory(LoadedApk.java:228)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:733)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:812)
        at android.app.LoadedApk.getResources(LoadedApk.java:1034)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2357)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5884)
        at android.app.ActivityThread.access$1200(ActivityThread.java:202)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1680)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:6878)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
    	Suppressed: java.io.IOException: Failed to open dex files from /data/app/com.zhangyue.ireader.asm_hook-2qV3WnGX1elKmKWhY32UGw==/base.apk because: Failure to verify dex file '/data/app/com.zhangyue.ireader.asm_hook-2qV3WnGX1elKmKWhY32UGw==/base.apk': Invalid type descriptor: 'Lcom\zhangyue\ireader\toolslibrary\handleThread\OptimizeThread;'
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:358)
        at dalvik.system.DexFile.<init>(DexFile.java:101)
        at dalvik.system.DexFile.<init>(DexFile.java:75)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:407)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:354)
        at dalvik.system.DexPathList.<init>(DexPathList.java:164)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:74)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:73)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:88)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:74)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:40)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:729)
        		... 12 more
2022-08-30 09:49:13.743 2482-2482/com.zhangyue.ireader.asm_hook E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.zhangyue.ireader.asm_hook, PID: 2482
    java.lang.RuntimeException: Unable to instantiate application com.zhangyue.ireader.asm_hook.MyApplication: java.lang.ClassNotFoundException: Didn't find class "com.zhangyue.ireader.asm_hook.MyApplication" on path: DexPathList[[zip file "/data/app/com.zhangyue.ireader.asm_hook-2qV3WnGX1elKmKWhY32UGw==/base.apk"],nativeLibraryDirectories=[/data/app/com.zhangyue.ireader.asm_hook-2qV3WnGX1elKmKWhY32UGw==/lib/arm64, /system/lib64, /system/vendor/lib64]]
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1073)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5988)
        at android.app.ActivityThread.access$1200(ActivityThread.java:202)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1680)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:6878)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.zhangyue.ireader.asm_hook.MyApplication" on path: DexPathList[[zip file "/data/app/com.zhangyue.ireader.asm_hook-2qV3WnGX1elKmKWhY32UGw==/base.apk"],nativeLibraryDirectories=[/data/app/com.zhangyue.ireader.asm_hook-2qV3WnGX1elKmKWhY32UGw==/lib/arm64, /system/lib64, /system/vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:171)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:50)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1121)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1065)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5988) 
        at android.app.ActivityThread.access$1200(ActivityThread.java:202) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1680) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:207) 
        at android.app.ActivityThread.main(ActivityThread.java:6878) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876) 
    	Suppressed: java.io.IOException: Failed to open dex files from /data/app/com.zhangyue.ireader.asm_hook-2qV3WnGX1elKmKWhY32UGw==/base.apk because: Failure to verify dex file '/data/app/com.zhangyue.ireader.asm_hook-2qV3WnGX1elKmKWhY32UGw==/base.apk': Invalid type descriptor: 'Lcom\zhangyue\ireader\toolslibrary\handleThread\OptimizeThread;'
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:358)
        at dalvik.system.DexFile.<init>(DexFile.java:101)
        at dalvik.system.DexFile.<init>(DexFile.java:75)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:407)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:354)
        at dalvik.system.DexPathList.<init>(DexPathList.java:164)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:74)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:73)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:88)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:74)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:40)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:729)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:812)
        at android.app.LoadedApk.getResources(LoadedApk.java:1034)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2357)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5884)
        		... 8 more
`
