### ISSUE TITLE
打开demo中build.gradle中隐私合规的注释之后，打开app闪退

### ISSUE THREAD

**Issue by markoZhang** [season-max/asm_hook#8]
报错如下：
2022-09-05 18:50:29.430 27665-27665/com.zhangyue.ireader.asm_hook E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.zhangyue.ireader.asm_hook, PID: 27665
    java.lang.RuntimeException: Unable to instantiate application com.zhangyue.ireader.asm_hook.MyApplication: java.lang.ClassNotFoundException: Didn't find class "com.zhangyue.ireader.asm_hook.MyApplication" on path: DexPathList[[zip file "/data/app/com.zhangyue.ireader.asm_hook-8T97AvTKmoxcwn3zN05EBw==/base.apk"],nativeLibraryDirectories=[/data/app/com.zhangyue.ireader.asm_hook-8T97AvTKmoxcwn3zN05EBw==/lib/arm64, /system/lib64, /product/lib64]]
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1183)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6688)
        at android.app.ActivityThread.access$2000(ActivityThread.java:273)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2020)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.zhangyue.ireader.asm_hook.MyApplication" on path: DexPathList[[zip file "/data/app/com.zhangyue.ireader.asm_hook-8T97AvTKmoxcwn3zN05EBw==/base.apk"],nativeLibraryDirectories=[/data/app/com.zhangyue.ireader.asm_hook-8T97AvTKmoxcwn3zN05EBw==/lib/arm64, /system/lib64, /product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:50)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1127)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1175)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6688) 
        at android.app.ActivityThread.access$2000(ActivityThread.java:273) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2020) 
        at android.os.Handler.dispatchMessage(Handler.java:112) 
        at android.os.Looper.loop(Looper.java:216) 
        at android.app.ActivityThread.main(ActivityThread.java:7625) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987) 
    	Suppressed: java.io.IOException: Failed to open dex files from /data/app/com.zhangyue.ireader.asm_hook-8T97AvTKmoxcwn3zN05EBw==/base.apk because: Failure to verify dex file '/data/app/com.zhangyue.ireader.asm_hook-8T97AvTKmoxcwn3zN05EBw==/base.apk': Invalid type descriptor: 'Lcom\zhangyue\ireader\toolslibrary\Util;'
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:354)
        at dalvik.system.DexFile.<init>(DexFile.java:101)
        at dalvik.system.DexFile.<init>(DexFile.java:75)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:394)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:354)
        at dalvik.system.DexPathList.<init>(DexPathList.java:164)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:74)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:73)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:88)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:84)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:40)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:801)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:884)
        at android.app.LoadedApk.getResources(LoadedApk.java:1135)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2623)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6595)
        		... 8 more

**Comment by hero0812** [comment]
> 报错如下： 2022-09-05 18:50:29.430 27665-27665/com.zhangyue.ireader.asm_hook E/AndroidRuntime: FATAL EXCEPTION: main Process: com.zhangyue.ireader.asm_hook, PID: 27665 java.lang.RuntimeException: Unable to instantiate application com.zhangyue.ireader.asm_hook.MyApplication: java.lang.ClassNotFoundException: Didn't find class "com.zhangyue.ireader.asm_hook.MyApplication" on path: DexPathList[[zip file "/data/app/com.zhangyue.ireader.asm_hook-8T97AvTKmoxcwn3zN05EBw==/base.apk"],nativeLibraryDirectories=[/data/app/com.zhangyue.ireader.asm_hook-8T97AvTKmoxcwn3zN05EBw==/lib/arm64, /system/lib64, /product/lib64]] at android.app.LoadedApk.makeApplication(LoadedApk.java:1183) at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6688) at android.app.ActivityThread.access$2000(ActivityThread.java:273) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2020) at android.os.Handler.dispatchMessage(Handler.java:112) at android.os.Looper.loop(Looper.java:216) at android.app.ActivityThread.main(ActivityThread.java:7625) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987) Caused by: java.lang.ClassNotFoundException: Didn't find class "com.zhangyue.ireader.asm_hook.MyApplication" on path: DexPathList[[zip file "/data/app/com.zhangyue.ireader.asm_hook-8T97AvTKmoxcwn3zN05EBw==/base.apk"],nativeLibraryDirectories=[/data/app/com.zhangyue.ireader.asm_hook-8T97AvTKmoxcwn3zN05EBw==/lib/arm64, /system/lib64, /product/lib64]] at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134) at java.lang.ClassLoader.loadClass(ClassLoader.java:379) at java.lang.ClassLoader.loadClass(ClassLoader.java:312) at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:50) at android.app.Instrumentation.newApplication(Instrumentation.java:1127) at android.app.LoadedApk.makeApplication(LoadedApk.java:1175) at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6688)  at android.app.ActivityThread.access$2000(ActivityThread.java:273)  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2020)  at android.os.Handler.dispatchMessage(Handler.java:112)  at android.os.Looper.loop(Looper.java:216)  at android.app.ActivityThread.main(ActivityThread.java:7625)  at java.lang.reflect.Method.invoke(Native Method)  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)  Suppressed: java.io.IOException: Failed to open dex files from /data/app/com.zhangyue.ireader.asm_hook-8T97AvTKmoxcwn3zN05EBw==/base.apk because: Failure to verify dex file '/data/app/com.zhangyue.ireader.asm_hook-8T97AvTKmoxcwn3zN05EBw==/base.apk': Invalid type descriptor: 'Lcom\zhangyue\ireader\toolslibrary\Util;' at dalvik.system.DexFile.openDexFileNative(Native Method) at dalvik.system.DexFile.openDexFile(DexFile.java:354) at dalvik.system.DexFile.(DexFile.java:101) at dalvik.system.DexFile.(DexFile.java:75) at dalvik.system.DexPathList.loadDexFile(DexPathList.java:394) at dalvik.system.DexPathList.makeDexElements(DexPathList.java:354) at dalvik.system.DexPathList.(DexPathList.java:164) at dalvik.system.BaseDexClassLoader.(BaseDexClassLoader.java:74) at dalvik.system.BaseDexClassLoader.(BaseDexClassLoader.java:65) at dalvik.system.PathClassLoader.(PathClassLoader.java:64) at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:73) at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:88) at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:84) at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:40) at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:801) at android.app.LoadedApk.getClassLoader(LoadedApk.java:884) at android.app.LoadedApk.getResources(LoadedApk.java:1135) at android.app.ContextImpl.createAppContext(ContextImpl.java:2623) at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6595) ... 8 more

解决问题没？
